package com.refugio.web.entity;
// Generated 04-10-2018 1:08:05 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Animal generated by hbm2java
 */
@Entity
@Table(name = "animal")
public class Animal implements java.io.Serializable {

	private Integer id;
	private Raza raza;
	private String nombre;
	private Date fechaIngreso;
	private float peso;

	public Animal() {
	}

	public Animal(Raza raza, float peso) {
		this.raza = raza;
		this.peso = peso;
	}

	public Animal(Raza raza, String nombre, Date fechaIngreso, float peso) {
		this.raza = raza;
		this.nombre = nombre;
		this.fechaIngreso = fechaIngreso;
		this.peso = peso;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "raza_id", nullable = false)
	public Raza getRaza() {
		return this.raza;
	}

	public void setRaza(Raza raza) {
		this.raza = raza;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ingreso", length = 10)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "peso", nullable = false, precision = 12, scale = 0)
	public float getPeso() {
		return this.peso;
	}

	public void setPeso(float peso) {
		this.peso = peso;
	}

}
