package com.refugio.web.entity;
// Generated 04-10-2018 1:08:05 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Familia generated by hbm2java
 */
@Entity
@Table(name = "familia")
public class Familia implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set<Raza> razas = new HashSet<Raza>(0);

	public Familia() {
	}

	public Familia(String nombre, Set<Raza> razas) {
		this.nombre = nombre;
		this.razas = razas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "familia")
	public Set<Raza> getRazas() {
		return this.razas;
	}

	public void setRazas(Set<Raza> razas) {
		this.razas = razas;
	}

}
